from find_person import find_person
from delete_all_people import delete_all_people
from delete_people import delete_person_by_name
from find_person import find_person
from add_person import add_person
from manage_people import change_person_details
from person import Person
from save_people import save_people
from load_people import load_people
from utils.compare_people import find_and_compare_people
from utils.get_total_age import get_total_age
from utils.get_total_people import get_total_people
from utils.sum_genders import genders_sum
from utils.compare_people import find_and_compare_people
from utils.choices_d import choice_d_options
from utils.choices_o import choice_o_options